// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/user.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	IsAdult              bool     `protobuf:"varint,4,opt,name=is_adult,json=isAdult,proto3" json:"is_adult,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_92db3b6f43600177, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetIsAdult() bool {
	if m != nil {
		return m.IsAdult
	}
	return false
}

type CreateRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	IsAdult              bool     `protobuf:"varint,3,opt,name=is_adult,json=isAdult,proto3" json:"is_adult,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92db3b6f43600177, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *CreateRequest) GetIsAdult() bool {
	if m != nil {
		return m.IsAdult
	}
	return false
}

type CreateResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsCreated            bool     `protobuf:"varint,2,opt,name=is_created,json=isCreated,proto3" json:"is_created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92db3b6f43600177, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateResponse) GetIsCreated() bool {
	if m != nil {
		return m.IsCreated
	}
	return false
}

type WithID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithID) Reset()         { *m = WithID{} }
func (m *WithID) String() string { return proto.CompactTextString(m) }
func (*WithID) ProtoMessage()    {}
func (*WithID) Descriptor() ([]byte, []int) {
	return fileDescriptor_92db3b6f43600177, []int{3}
}

func (m *WithID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithID.Unmarshal(m, b)
}
func (m *WithID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithID.Marshal(b, m, deterministic)
}
func (m *WithID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithID.Merge(m, src)
}
func (m *WithID) XXX_Size() int {
	return xxx_messageInfo_WithID.Size(m)
}
func (m *WithID) XXX_DiscardUnknown() {
	xxx_messageInfo_WithID.DiscardUnknown(m)
}

var xxx_messageInfo_WithID proto.InternalMessageInfo

func (m *WithID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsDeleted            bool     `protobuf:"varint,2,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92db3b6f43600177, []int{4}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteResponse) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "protos.User")
	proto.RegisterType((*CreateRequest)(nil), "protos.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "protos.CreateResponse")
	proto.RegisterType((*WithID)(nil), "protos.WithID")
	proto.RegisterType((*DeleteResponse)(nil), "protos.DeleteResponse")
}

func init() { proto.RegisterFile("protos/user.proto", fileDescriptor_92db3b6f43600177) }

var fileDescriptor_92db3b6f43600177 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xd9, 0xa4, 0xc6, 0x74, 0xd4, 0xa0, 0x0b, 0xca, 0x1a, 0x10, 0x42, 0xbc, 0xe4, 0x54,
	0x45, 0x0f, 0x1e, 0xa5, 0x58, 0x10, 0xaf, 0x2b, 0xa2, 0xb7, 0x10, 0xbb, 0x83, 0x5d, 0xa8, 0x4d,
	0xdd, 0xd9, 0xf8, 0x6f, 0xfc, 0xaf, 0x92, 0x5d, 0x53, 0x4c, 0x5b, 0xe8, 0x6d, 0x66, 0xf2, 0xe6,
	0x7b, 0x99, 0x7d, 0x70, 0xb2, 0x34, 0xb5, 0xad, 0xe9, 0xaa, 0x21, 0x34, 0x23, 0x57, 0xf3, 0xc8,
	0x8f, 0xf2, 0x12, 0x06, 0x2f, 0x84, 0x86, 0x27, 0x10, 0x68, 0x25, 0x58, 0xc6, 0x8a, 0xa1, 0x0c,
	0xb4, 0xe2, 0x29, 0xc4, 0xad, 0x7a, 0x51, 0x7d, 0xa2, 0x08, 0xdc, 0x74, 0xd5, 0xf3, 0x63, 0x08,
	0xab, 0x0f, 0x14, 0x61, 0xc6, 0x8a, 0x3d, 0xd9, 0x96, 0xfc, 0x1c, 0x62, 0x4d, 0x65, 0xa5, 0x9a,
	0xb9, 0x15, 0x83, 0x8c, 0x15, 0xb1, 0xdc, 0xd7, 0x34, 0x6e, 0xdb, 0xfc, 0x0d, 0x8e, 0x1e, 0x0c,
	0x56, 0x16, 0x25, 0x7e, 0x35, 0x48, 0xb6, 0x47, 0x66, 0xdb, 0xc9, 0xc1, 0x76, 0x72, 0xd8, 0x27,
	0xdf, 0x43, 0xd2, 0x91, 0x69, 0x59, 0x2f, 0x08, 0x37, 0x8e, 0xb8, 0x00, 0xd0, 0x54, 0x4e, 0x9d,
	0x48, 0x39, 0x6a, 0x2c, 0x87, 0x9a, 0xfc, 0x96, 0xca, 0x05, 0x44, 0xaf, 0xda, 0xce, 0x9e, 0x26,
	0xeb, 0x8b, 0x2d, 0x7a, 0x82, 0x73, 0xdc, 0x89, 0x56, 0x4e, 0xf4, 0x0f, 0xed, 0xb7, 0xd4, 0xcd,
	0x0f, 0x83, 0x83, 0x71, 0x63, 0x67, 0xcf, 0x68, 0xbe, 0xf5, 0x14, 0xf9, 0x1d, 0x44, 0xde, 0x95,
	0x9f, 0xfa, 0x00, 0x68, 0xd4, 0x7b, 0x95, 0xf4, 0x6c, 0x7d, 0xfc, 0xe7, 0x7b, 0x09, 0xe1, 0x23,
	0x5a, 0x9e, 0x74, 0x9f, 0xfd, 0x0f, 0xa7, 0x87, 0x5d, 0xef, 0xc2, 0xbb, 0x86, 0xc8, 0x1b, 0x6f,
	0xe8, 0x56, 0xd8, 0xfe, 0x39, 0xef, 0x3e, 0xfe, 0xdb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x48,
	0xc6, 0x22, 0x9a, 0x1a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Get(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*User, error)
	Delete(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/protos.AuthService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Get(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/protos.AuthService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Delete(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/protos.AuthService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Get(context.Context, *WithID) (*User, error)
	Delete(context.Context, *WithID) (*DeleteResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedAuthServiceServer) Get(ctx context.Context, req *WithID) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedAuthServiceServer) Delete(ctx context.Context, req *WithID) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AuthService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AuthService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Get(ctx, req.(*WithID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AuthService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Delete(ctx, req.(*WithID))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AuthService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AuthService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AuthService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/user.proto",
}
